### ISSUE TITLE
Request // Auto-sudo for commands that require it

### ISSUE THREAD

**Issue by derek-shnosh** [convergeone/freeztp#33]
The ztp service commands seem to automatically prompt for sudo creds if needed.

Other commands do not, e.g. ztp set external-keystore or any other command that modifies the config.

**Comment by PackeTsar** [comment]
This is because `ztp service` actually runs a BASH command behind the scenes which prompts for the password. I don't think it is possible to privesc from within the Python code. You may just want to permanently escalate your permission (using the `su` command) so you don't have to use sudo constantly here.
