### ISSUE TITLE
Request - Dynamic use of multiple imagefiles

### ISSUE THREAD

**Issue by NaorCH** [convergeone/freeztp#37]
Hello,

Could it be possible for freeztp to auto assign an imagefile based on the hardware type of the switch being provisioned?

For instance, using SNMP to query the switch model (in addition to it's unique ID), and using this information while generating the imagediscoveryfile (pointing to the correct image file) per switch.

I believe this functionality would be extremely useful for anyone who uses freeztp, including me.

Thank you very much for your time and effort,
Naor

**Comment by derek-shnosh** [comment]
Unfortunately this isn't possible because the first thing the switch does is request an image, which FreeZTP will provide if `imagediscoveryfile-option` is set to `enable`; i.e. `ztp set dhcpd SCOPENAME imagediscoveryfile-option enable`.

The SNMP query isn't possible until after the `initial config` is given to the switch, which doesn't happen until after the image request.

@PackeTsar may have more input here, but that's pretty much the rub.

Good news is that the [Upgrade workaround in the Usage Tips](https://github.com/PackeTsar/freeztp/blob/latest/TIPS.md#required-config) can be used to accomplish your goal. Just assign the image file in your keystore or the template and let it rip.

~~This reminds me, I've got an updated version of that applet that checks whether an upgrade is needed before actually doing the upgrade.~~ *Updated.*

**Comment by PackeTsar** [comment]
Yea @derek-shnosh nailed it here. If FreeZTP is ever extended to support PnP, then this might be a possibility. Until then, the way suggested by @derek-shnosh is the only way to do it.
