### ISSUE TITLE
Reason to push an intial config and a final config?

### ISSUE THREAD

**Issue by ayuanx** [convergeone/freeztp#40]
Hi,

I am wondering why you use an intial config and a final config.
Is there any specific purpose for that? Or is it simply a procedure requied by the hardware?

Why not use just  one final config? Wouldn't that make things much simpler?

Thanks!

**Comment by PackeTsar** [comment]
The initial config's purpose is to prepare the switch for discovery by ZTP. The initial config sets a SNMP community on the switch, which ZTP then uses to query the switch for its serial number. Since ZTP is able to build a template using variables assigned to the switch's serial number, it needs a way to discover the serial number of the switch, match it up with the appropriate variables (in a keystore), and then be able to render the final config for the switch once the switch requests it.

**Comment by PackeTsar** [comment]
For more detailed information on this, check out the [ZTP Process section of the README](https://github.com/PackeTsar/freeztp#ztp-process)

**Comment by ayuanx** [comment]
Thanks! So the initial config is only used as a method to identfy the switch.

I guess if we can use the mac address from that bootup DHCP request to identify the switch, we can push its corresponding final config directly to it, saving the SNMP procedure and a second config push.

**Comment by PackeTsar** [comment]
That could be possible, but may also be more difficult to do. The switch's MAC on the VLAN1 SVI may change slightly from the burned in MAC so you would have to try to predict that. Also, it would be impossible to use a different server as the DHCP server, which may have to be the case if you are deploying switches in an already established network.

**Comment by ayuanx** [comment]
I see. Thanks. I guess this approach is for Cat3K.
For Cat9K, DHCP option 150 and 67 allow you to provide a URL to a Python script instead of a config file of predefined name, and there is no mentioning of DHCP option 125, so things are somewhat different.
