### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by smolit** [convergeone/freeztp#61]
Hi John and Derek,

I am impressed by the freeztp project and I am very grateful for your work.
Have you planned to make freeztp compatible to Python 3?

Cheers
Sebastian

**Comment by PackeTsar** [comment]
This is a great question. I originally started writing it in Py3 but had to move down to Py2 due to the TFTPy library not supporting Py2 (it was getting old and unmaintained at the time). That is why you see FreeZTP use my very slightly modified fork of TFTPy.

Since then, the maintainer has put a lot of work into bringing it current and supporting Py3.

I am adding this request into https://github.com/PackeTsar/freeztp/issues/24 to track it as a goal for v2 of FreeZTP if it ever happens.
